#!/usr/bin/env sh

##########################
# ] ---- AUTOSTART ---- [#
##########################

# polkit for gui app
#exec /usr/libexec/polkit-mate-authentication-agent-1 &

# start gnome-keyring
#eval $(gnome-keyring-daemon --start)
#export SSH_AUTH_SOCK

# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# start GUI compositor picom
picom --experimental-backends &

# polybar
# bash ~/.config/polybar/launch.sh --onedark &

# start notifier
# dunst &

# start lockscreen
#betterlockscreen -l &


######################
# ] ---- PYWAL ---- [#
######################

#picture="jellyspace.jpg"
#wal_path="$HOME/Pictures/Wallpapers/"
#wallpaper="$wal_path$picture"

# set desktop wallpaper
#feh --bg-scale "$wallpaper" &

# pywal & walpg modify color schema
#wal -i "$wallpaper" -q -t &
#wpg -a "$wallpaper" &
#wpg -s "$picture" ;

# screen lock and sleep if user is not active
#xidlehook --not-when-fullscreen --timer 900 'betterlockscreen -l' '' &
#xidlehook --not-when-fullscreen --timer 3600 'loginctl suspend' '' &

# Change the color scheme for apps
#cp ~/.cache/wal/colors-alacritty.yml ~/.config/alacritty/color.yml
#cp ~/.cache/wal/colors-polybar.ini ~/.config/polybar/zebra/colors.ini &
#cp ~/.cache/wal/colors-cava.conf ~/.config/cava/config
#cp ~/.cache/wal/colors-mellowplayer.conf ~/.config/MellowPlayer/MellowPlayer3.conf

# Keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ru &

###########################
# ] ---- WORKSPACES ---- [#
###########################

bspc monitor -d I II III IV V VI VII VIII IX X

##############################
# ] ---- WINDOW CONFIG ---- [#
##############################

bspc config window_gap           15
bspc config border_width         0

#bspc config border_width         3
#bspc config normal_border_color "#2A2426"
#bspc config focused_border_color "#87AF87"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Remove x cursor
xsetroot -cursor_name left_ptr &
